### ISSUE TITLE
Blank user alert on account creation, when UF5 can't connect to SMTP

### ISSUE THREAD

**Issue by StrykeSlammerII** [alexweissman/UserFrosting#1229]
Version and OS: UF 5, native install, Firefox, Linux (Arch)

PROBLEM:
When a new user attempts to create an account, but UF can't connect to an SMTP server, the user receives a blank alert popup.
(The user is still created.)
![image](https://github.com/userfrosting/UserFrosting/assets/16699223/2aa45430-0366-4097-af31-fdbbd1e36a04)

EXPECTED RESULTS:
A blank error message is unhelpful.
At least it could alert the user that there is an issue with the webpage and the account was not created.

In my test, `app/logs/userfrosting.log` showed successful DB queries, but UF could not connect to SMTP server:
```[2023-10-31T01:50:59.474835-04:00] mail.DEBUG: Connection: opening to 0.0.0.0:1025, timeout=15, options=array() [] []
[2023-10-31T01:50:59.474993-04:00] mail.DEBUG: Connection failed. Error #2: stream_socket_client(): Unable to connect to 0.0.0.0:1025 (Connection refused) [/home/strike/Frosting/UF5-native/vendor/phpmailer/phpmailer/src/SMTP.php line 396] [] []
[2023-10-31T01:50:59.475037-04:00] mail.DEBUG: SMTP ERROR: Failed to connect to server: Connection refused (111) [] []
[2023-10-31T01:50:59.484563-04:00] mail.DEBUG: SMTP Error: Could not connect to SMTP host. Failed to connect to server [] []
[2023-10-31T01:50:59.485549-04:00] errors.ERROR: UserFrosting Application Error:
Type: PHPMailer\PHPMailer\Exception
Message: SMTP Error: Could not connect to SMTP host. Failed to connect to server
File: /home/strike/Frosting/UF5-native/vendor/phpmailer/phpmailer/src/PHPMailer.php
Line: 2233
Trace: #0 /home/strike/Frosting/UF5-native/vendor/phpmailer/phpmailer/src/PHPMailer.php(2019): PHPMailer\PHPMailer\PHPMailer->smtpConnect()
[etc]
```

Root user can't see the new account via the web interface. I have not been able to check the database directly to see whether a partial account exists there.

(In my case the SMTP server was not running, so everything aside from the empty user alert appears to be correct.)

**Comment by lcharette** [comment]
I added a try/catch to catch `PHPMailerException` and add a proper warning in https://github.com/userfrosting/sprinkle-account/commit/836a3a269bf095f80ad21962573dbf8c72025b5b. 

It's a "temporary" solution, as the actual warning is already returned in the request body, but not properly handled by [`uf-form.js`](https://github.com/userfrosting/theme-adminlte/blob/8cf98bffb2a48bfaa84eeb91787221cc377045f1/app/assets/userfrosting/js/uf-form.js#L230). By default `_debugAjax` is off and the exception doesn't have a description (but it doesn't matter, since _debugAjax is off), so nothing was displayed. The whole ufForm need to be rewritten, and it's planned for UF6 with Vue.js, so I won' waste more time on this for now and went with this "temp" fix.
