### ISSUE TITLE
page not loading styles outside of fw

### ISSUE THREAD

**Issue by bigchoice** [alexweissman/UserFrosting#177]
Hi,
I have a strange problem. When I am loading userfrosting site from internal network (any computer on inside network) it loads all css styles perfectly. When I load from outside my firewall ie on the internet, it takes a minute or  two to load page and when it does,  it does not load css styles. It's very strange. It does not appear to be firewall issue since i can connect to webserver and get response. my website_url is configured with '10.1.1.1/mysite'.  Any ideas?

**Comment by bigchoice** [comment]
Hey alex,
I'm having a weird issue that is driving me nuts! I cannot track this down for the life of me! When a user is registering for an account, after they fill out the form the click 'register' and the page throws an error saying something something went wrong and check php logs. I notice the following in php log:
[Wed Apr 06 16:30:45 2016] [error] [client 1.1.1.1] script '/var/www/html/folder/models/captcha.php' not found or unable to stat, referer: http://www.oddahi.com/folder/register.php
The user account is registered and email sent but they get this error message instead of the friends 'user account has been registered...etc etc..' Any ideas?

**Comment by alexweissman** [comment]
@bigchoice this version of UF (looks like 0.2.x) is no longer being supported.  Any chance you can migrate your site to 0.3.1?

**Comment by bigchoice** [comment]
Alex,
I installed UF 3.1-78 which is the latest version on the website. I am having a couple issues, which may or may not be 'by design'. I am wondering where the 'page authorization' page has gone? Under 'Configuration' the only options are now 'site settings' and 'groups'.   Did you get rid of this in newer version? I also tried to delete the 'Zerlings' group but it did not remove the 'Zerlings' link on left side of page. When I click it I get a 404 error. I would think the link should be deleted after removing group. I also tried to register an account after installation but it threw an smtp error. I had postfix configured with older version of userfrosting and it worked flawlessly. I did not input the smtp information during setup and addded it to config-userfrosting.php afterwards, is this problematic? should i reinstall with the smtp settings?

**Comment by alexweissman** [comment]
@bigchoice have you gone through the [tutorials](http://userfrosting.com/tutorials)?

"Page authorization" is no longer a separate thing; it's been subsumed into [authorization hooks](http://www.userfrosting.com/components/#authorization).  It didn't make sense to distinguish between page-level and other authorization methods, because we are no longer thinking in terms of "pages".  Instead, we should think in terms of "resources" (a page is just one type of resource).  You can change permissions for different authorization hooks in Groups, in the dropdown menus for each group.

The Zerglings link is just an example of how you can add custom views for different groups.  There is no intention for UF to automatically add/remove pages like this for each group (and I suspect that for most use cases, that would actually just be really annoying).  If you want to remove it, simply remove the link from the sidebar template: https://github.com/userfrosting/UserFrosting/blob/master/userfrosting/templates/themes/default/components/dashboard/menus/sidebar.twig#L28-L32

For mail, you can try setting the `mail` setting in `config-userfrosting.php` to `sendmail`.  This is not currently a very well documented feature.
