### ISSUE TITLE
Custom User Field Usage

### ISSUE THREAD

**Issue by jpietrick** [alexweissman/UserFrosting#196]
Hi all,

First of all really do like your software. I am just started programming and learning a lot from the code. I followed the tutorial to add a custom user field and was successful. I created a field called sun_id and it is a varchar 10. I need to use this field to reference calls to another database. I tried setting it to a variable such as 
$sunid= $loggedInUser->sun_id; Which didn't work. Wondering if anyone can help me out or point me in the right direction.

Thank you

**Comment by alexweissman** [comment]
Awesome, welcome to the UF community!  The `loggedInUser` object is created in `api/process_login.php`.  So, for now you can add your new field to the `loggedInUser` class in `models/class.user.php` and then set it in `process_login.php`.

The reason I say "for now" is because we are working on a new version of UF which should take care of these things automatically, and hopefully make it a lot easier to add new user fields, and work with UF in general, in the future.

Let me know if you run into any more difficulties!

**Comment by jpietrick** [comment]
Alex,



I did add the field in class.user.php before  but I did not set it in the
process_login.php.Once I did that it worked like  a charm. Thank you so
much.



*From:* Alex Weissman [mailto:notifications@github.com]
*Sent:* Wednesday, January 7, 2015 6:02 PM
*To:* alexweissman/UserFrosting
*Cc:* jpietrick
*Subject:* Re: [UserFrosting] Custom User Field Usage (#196)



Awesome, welcome to the UF community! The loggedInUser object is created in
api/process_login.php. So, for now you can add your new field to the
loggedInUser class in models/class.user.php and then set it in
process_login.php.

The reason I say "for now" is because we are working on a new version of UF
which should take care of these things automatically, and hopefully make it
a lot easier to add new user fields, and work with UF in general, in the
future.

Let me know if you run into any more difficulties!

—
Reply to this email directly or view it on GitHub
<https://github.com/alexweissman/UserFrosting/issues/196#issuecomment-69115110>
.

**Comment by alexweissman** [comment]
Awesome, glad I was able to help.  Good luck with your project!
