### ISSUE TITLE
How to POST a form?

### ISSUE THREAD

**Issue by ericksonstudio** [alexweissman/UserFrosting#207]
Thank for creating UserFrosting! I'm loving the ease of setup and security features.

Here's my dilemma: I created a web app, but am integrating UserFrosting at the end of the project (I wish I had started with UF instead, but alas...). Because of that, I have already existing functions in a separate directory/file for _POSTing form data to write to a MySQL database. Now those functions won't work because of validation I believe?

So the question is, how do I POST form data?

(I've poked around the code, and read on this website, but I'm still clueless and I'm at my coffee quota). Thanks in advance for any help you may provide!

    $conn->autocommit(FALSE);
    $projectupdate = "UPDATE tan_projects SET company_name='$edit_project_name' WHERE coid='$edit_project_id' LIMIT 1";
    $conn->query($projectupdate) or die(mysqli_error($conn));
    $projectq = $conn->query("SELECT coid,company_name FROM tan_projects WHERE coid='$edit_project_id'") or die(mysqli_error($conn));
    $project = $projectq->fetch_assoc();
    if(!$conn->commit()){
        print("Save failed.\n");
        exit();
    }
    echo $project['company_name'];
    $conn->autocommit(TRUE);

**Comment by alexweissman** [comment]
Hi @ericksonstudio , welcome to UF!  

You should be able to call your DB functions instead of the built-in UF functions pretty easily.  Basically, forms are POSTed to one of the "api" pages, in the `api` directory.  So, I would start by taking a look at how the current API pages work, for example `api/update_user.php`, and try to adapt that pattern for your own form.

I should point out that as it stands, your DB function is vulnerable to SQL injection if `$edit_project_name` is a user-provided input.  If you don't know what SQL injection is, the Wikipedia article explains it pretty well.  

If you take a look at the functions in `models/db_functions.php`, you can see how we prevent SQL injection by using PDO to bind parameters to SQL queries.  It's pretty easy, and I strongly recommend you follow that pattern.  Otherwise, any kid can delete your entire database through your form ;-)

**Comment by ericksonstudio** [comment]
I knew you were gonna say that about the injection issue! I should have added a caveat that I posted the way I did to keep things simple. Thanks for having my back on that anyway. :)

**Comment by alexweissman** [comment]
Bwahaha.  Let me know if you run into any more trouble as you are implementing your POST solution.

**Comment by ericksonstudio** [comment]
Hmm...taking update_user.php as an example, which lines are required to put into my own function? Lines 32 through 70?

**Comment by alexweissman** [comment]
Honestly, I wouldn't use the `Validator` class since we'll be deprecating it in the next edition.  Use the `Valitron` validation system instead.  See the `validateSiteSettings` function in `validation/validate_form.php` for a better way to do validation.

**Comment by ericksonstudio** [comment]
Okay, so basically...I have to create my own API function, similar to update_user.php, in order to use my own functions? Correct or no?

**Comment by alexweissman** [comment]
Yup, each object should get it's own API.  A couple things:

- There are two things that need to be done before you insert data into the database: validating the POSTed data and checking user permissions.  Right now, the validation is taken care of directly in the API files (e.g. `update_user.php`).  The functions that are called from there like `updateDisplayName` automatically take care of checking permissions by calling the `checkPermissionSelf` function.
- You'll notice that in `update_user.php`, we have a separate function for updateDisplayName, updatePassword, etc.  The reason I did this is to allow fine-grain permissions control over each field.  If you don't need that kind of control, you can probably get away with a more generic `updateProject` function or the like.
- If you want to get fancy, you can start playing around with a routing library like [Klein](https://github.com/chriso/klein.php).  That way, you could have it automatically generate URLs like `http://yoursite.com/projects/11/update/`, rather than having to make a separate file for each type of object.

**Comment by alexweissman** [comment]
Let us know if you have any more problems!
