### ISSUE TITLE
IE 8 issue with design and updating user login details

### ISSUE THREAD

**Issue by damirser** [alexweissman/UserFrosting#226]
Hi,

just opened my project based on UF in Internet Explorer 8, and I found an issue with design as it is showing the whole site like it is on a mobile device, and also it doesn't load input field values under login settings (email field). Plus when I click Update button it takes me to update_user.php and shows it as 404 page. 

Does anyone know what seems to be an issue??

Thanks!

**Comment by alexweissman** [comment]
Ugh, IE.  I guess we should support it, though!  We probably just need to use the [HTML5 Shim](https://html5shim.googlecode.com/svn/trunk/html5.js) which is designed to bring IE up to speed with other browsers.  Want to give it a try and let us know if it works?

**Comment by jeffpowell** [comment]
I've been able to reproduce this as well.  Pulling either the one provided or the non-minified version from that project does not fix the issue.

**Comment by alexweissman** [comment]
Interesting.  Does IE8 have a Javascript console that you can check for errors?  Well I guess, technically it'd be JScript ;-)

**Comment by jeffpowell** [comment]
That was using IE 11, using the Developer Tools to emulate IE 8.  The console didn't show any errors, though if IE 8 doesn't have a console, the emulation may take that into account.  I had to remove a bunch of console.log() calls because I had a bunch of users on IE 8 who couldn't log in - they'd just get an "error on this page" message.

**Comment by alexweissman** [comment]
Well, based on what you're describing it sounds like IE8 might be having trouble handling the AJAX requests - especially if its trying to forward you to a page when you click "Update" (it's supposed to be submitting the request via AJAX and then simply reloading the page).

What happens if you try setting `cache: false` in the AJAX requests as per [this article](http://www.itworld.com/article/2693447/development/ajax-requests-not-executing-or-updating-in-internet-explorer---solution.html)?

**Comment by jeffpowell** [comment]
Using <pre>$.ajaxSetup({ cache: false });</pre> at the top of userfrosting.js does not solve the issue (either on its own or in conjunction with the HTML5 shim).

**Comment by alexweissman** [comment]
How about [respond.js](http://www.zell-weekeat.com/support-for-older-browsers/)?  At the very least, that might solve the issue with the page rendering with the mobile sizes.

**Comment by alexweissman** [comment]
Microsoft itself is [dropping support for IE8 in about 6 months](http://www.techtimes.com/articles/12722/20140811/17-months-until-ie8-support-ends.htm).  I would say, let's not worry about this going forward.
