### ISSUE TITLE
Contact form

### ISSUE THREAD

**Issue by tarek-sendi** [alexweissman/UserFrosting#238]
Hi,
I'm new user of UserForsting i need help to make contact form with an api to send this the message to the website admin.
contact.php
/api/contact_form.php

Thanks UserForsting Team.

**Comment by alexweissman** [comment]
I would suggest that you start with an existing form, like that in `account/account_settings.php`, and try to adapt it from there.  You'll need to create a backend API page as well to process the request.  But, instead of inserting into the database, you'll use the `mail` function to send it to the website admin.  Let me know if you get stuck on any specific point, and welcome to UF.

**Comment by alexweissman** [comment]
Let me know if you need any more help!
