### ISSUE TITLE
versioning / version numbers / semantic versioning

### ISSUE THREAD

**Issue by anthonybartoli** [alexweissman/UserFrosting#280]
I ran across [Tom Preston-Werner's Semantic Versioning](http://semver.org/) which got me wondering about the version numbering. Should UF not be at 1.0.0 once it uses Twig, Slim, and RedBean? Is there a particular rationale to the current numbering you've used up until now?

**Comment by alexweissman** [comment]
I'm using the ["version 1 as a milestone"](https://en.wikipedia.org/wiki/Software_versioning#Version_1.0_as_a_milestone) numbering scheme.  I'd say that we should reserve 1.0.0 for after the rebuild but also after all the major bugs (because, there will almost definitely be bugs) have been dealt with.
