### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by gaiusjaugustus** [alexweissman/UserFrosting#287]
Filled in the information about my database.  Then went to /install and pressed "Install".  Upon navigating to wizard_site_config.php, I get the following error:

"Internal Server Error
The server encountered an internal error or misconfiguration and was unable to complete your request.
Please contact the server administrator, and inform them of the time the error occurred, and anything you might have done that may have caused the error.
More information about this error may be available in the server error log."

Error log states an issue in func.php: 
HP Parse error: syntax error, unexpected '[' in /models/funcs.php on line 63

**Comment by alexweissman** [comment]
What version of PHP are you running?

**Comment by gaiusjaugustus** [comment]
PHP 5.3.  Is that too outdated?  (I had this issue with another login script I tried, too.  So sad)

**Comment by alexweissman** [comment]
Give them a call, most webhosts will do the upgrade for you!

**Comment by gaiusjaugustus** [comment]
So I just spoke with my webhost, and they're updating the system for me.  Yay!  Is there an easy way to upgrade to UF (can I just install and then drop all my custom files + db config files in?  can I upgrade right on top of usercake?)  or will I need to go into my files and change things individually?

Thanks again for your help.

**Comment by alexweissman** [comment]
Cool, that's great!  Upgrading to UF from UC may be a little bit tricky because the database structures are different.  UF has a lot of tables that are not found in UC, and some tables (such as `users`) have new columns.  Others (like `groups`) have been renamed.

My advice would be to start with a clean install of UF in your dev environment, and then gradually import the contents of your existing website.  For the database, you can export your current tables, rename them as necessary in the resulting SQL code, and then try to import them into UF.

I'm holding off on developing a UC import tool, mainly because the next version of UF will also have a slightly different DB structure.

**Comment by alexweissman** [comment]
Let me know if you have any more problems!
