### ISSUE TITLE
Page switch flicker

### ISSUE THREAD

**Issue by killent** [alexweissman/UserFrosting#294]
How to resolve from one menu to other menu the page will blank white for a while ?
Thanks!
---

**Comment by alexweissman** [comment]
Do you mean the entire page, or just the tables and widgets?

**Comment by killent** [comment]
tables and widgets

**Comment by alexweissman** [comment]
The only way to deal with this would be to render the entire page in one request, rather than each widget separately.  I originally did this because I figured it was better to see at least part of the page while waiting for the rest of it to load.  

We could either do the "entire page in one shot" approach, or stick with the current approach but show a "loading" icon.
