### ISSUE TITLE
Folder Structure Suggestion for 0.3.0

### ISSUE THREAD

**Issue by leanpanda** [alexweissman/UserFrosting#312]
Thanks for UserFrosting. Have been using UserCake for a while now and switched to UserFrosting and it is great.

Quick Suggestion here on the folder structure for 0.3.0 (and maybe this is already implemented in 0.2.0 and I'm just missing it): Allow the page-level authorization to point to folders other than account and forms, especially to folders that are outside the UserFrosting tree, for example in this tree:

public/
├── userfrosting/
│   ├── account/
│   ├── forms/
│   ├── js/
│   ├── models/
│   ├── api/
│   ├── css/
│   ├── upgrade/
├── milleniumfalcon/ 
│   ├── shield_control/
│   ├── sensor_jammers/
│   ├── hologram_board/
│   ├── power_generators/
│   ├── hyperdrive/

If we can point userfrosting's site_authorization.php to also scan shield_control for new PHP files then we  avoid having to move all of milleniumfalcon pieces under userfrosting/account 

Also when userfrosting gets updated to 0.3.1 or milleniumfalcon gets updated (to episode VII) only one of those folders needs to get updated without having to do much with the other one.

Looking forward to 0.3.0. Thanks again for the great work.

**Comment by alexweissman** [comment]
Hehe, love your versioning system for milleniumfalcon!  

Authorization for 0.3.0 will be tied to URI's, rather than individual PHP files.  This is because 0.3.0 will use URL routing, so there will no longer be a one-to-one correspondence between files and URIs.  All page requests will be handled by a single controller, which will first check the user's authorization and then return the appropriate page.

So in your case, you will want to prevent clients from directly accessing files in the `milleniumfalcon` directory.  You can do this by putting `milleniumfalcon` outside of the `public` folder entirely (the UF core files are also being moved out the `public` folder).  Then, you'll modify UF's controller to accept `milleniumfalcon`-related URI's, and call the relevant pieces of code inside `milleniumfalcon` to generate those pages.

You can see the new structure for UF in the [slim branch](https://github.com/alexweissman/UserFrosting/tree/slim).  All the core UF files will be located in the `userfrosting` folder.  You could put `milleniumfalcon` at the same level.

**Comment by leanpanda** [comment]
Thanks for the fast response. I'm not familiar to what URL Routing would do to the novice developer workflow or for when situation, in my case UserFrosting is not at the center of the application and is instead being "in the periphery" used primarily for registration and authentication. For example:

#### With 0.2.2: 

The workflow today is for the Developer (or me from my coding environment) is three steps:
- <b>write:</b> activate_shields.php
- <b>place at the beginning:</b>`!securePage(__FILE__)`
- <b>save in folder</b>  milleniumfalcon/shield_control/
- <b>Done</b> 

For the site admin (or me from my phone) is two:
- <b>navigate to:</b>  SiteSettings/Authorization/Page-level_authorization
- <b>on the line that says activate_shields.php</b> check the box for Wookies, leave blank the box for Droids

#### With 0.3.0 and URL Routing

- will the Developer be able to add a new file, like activate_hyperdrive.php without having to decide in code who can use it?
- can the Admin assign who can active hyperdrives, without having to touch code?

Hope this helps.

**Comment by alexweissman** [comment]
Yup, the workflow will be almost the same.  Instead of putting `activate_hyperdrive.php` in a publicly accessible folder and adding `securePage(__FILE__)` at the top, you'd put `activate_hyperdrive.php` in a private folder and then write a small controller associated with a particular URL (for example, `http://rebels.com/milleniumfalcon/hyperdrive/activate` that calls this file (the simplest way would be to simply `include` it).  UF's routing system will automatically check permissions when someone navigates to the associated URL.  

Permissions will still be controllable from an admin interface, and won't require a developer to modify the code.

**Comment by leanpanda** [comment]
nice. thanks. can't wait for 0.3.0

**Comment by alexweissman** [comment]
If you want a sneak preview, I've started concocting the authorization system for the next version.  Basically, there is a class `MySqlUser` with a method `checkAccess`: https://github.com/alexweissman/UserFrosting/blob/slim/userfrosting/models/mysql/MySqlUser.php#L89

What you'll do is, at the beginning of the controller, do a check like `$loggedInUser->checkAccess('uri_activate_shields')`

Then you'll be able to associate groups with the `uri_activate_shields` hook.  The only drawback is that you'll probably have to manually register the `uri_active_shields` hook somewhere, in order to be able to assign users/groups to it from the admin interface.

This is because there will no longer be a one-to-one mapping of URIs to files, so we can't just scan the directory like we've been doing.

**Comment by leanpanda** [comment]
Thanks for the update. Will take you up on the sneak peek and review later tonight.

From your explanation I understand the added benefit is that at a coding level the developer can "filter" for happy Wookies. Seems like the two main tradeoffs then are about the workflow for the developer (now the developer is the one who makes group associations with additional step of registering uri_activate_shields in list_of_hooks.php) and the entry level PHP developers need to learn about creating and debugging hooks (as opposed to just adding files to directories)

**Comment by alexweissman** [comment]
Yup, you got it exactly right.  Slim (the routing engine) actually supports named routes, so it might be possible to define the hooks in the same line of code where you define the route.  In this case, we might be able to at least (partially) automate it.

**Comment by alexweissman** [comment]
Ok, see you at the v0.3.0 release!
