### ISSUE TITLE
0.3.0 Ajax Best Practices -- Server Side

### ISSUE THREAD

**Issue by r3wt** [alexweissman/UserFrosting#322]
Move all ajax related routes to an universal ajax controller.

Example of how this works:
https://github.com/r3wt/StarterKit/blob/master/libs/routes.php#L11
```php
$app->map('/ajax/:method',function($method) use($app){
 (new AjaxController)->_try($method);
})->via('GET','POST');
```

https://github.com/r3wt/StarterKit/blob/master/libs/StarterKit/Routes/AjaxController.php

Ajax controller extends JSON Controller...

https://github.com/r3wt/StarterKit/blob/master/libs/StarterKit/Routes/JsonController.php

Methods in Ajax class should either return an array in the format of
```
['error'=>0,'message'=> whatever you want to put here, can be an object can be a message  ]
```
or throw an exception. the Json controller will catch exceptions and output

```
['error'=>1,'message'=>$e->getMessage()]
```

**Comment by alexweissman** [comment]
Actually, I have redesigned the system so that we generate an appropriate HTTP status code (other than `200`) when an AJAX-related route fails for some reason.  For example, the `login` route halts with an error code of `403` when an incorrect password is entered, for example: https://github.com/alexweissman/UserFrosting/blob/dev-0.3.0/userfrosting/controllers/accountcontroller.php#L189.

Then, it can be easily caught by the `.fail()` callback.  IMO, this is the "correct" way to deal with different types of responses from an AJAX request.  Also, we don't usually want to rely on the response body itself for the actual error/success message.  This is because, in some situations, we might not be ready to use the message immediately.  Having a separate message stream (`/alerts`) lets us fetch failure/success messages whenever we want, even after a page refresh.

**Comment by alexweissman** [comment]
Note also that the use of HTTP response codes is the correct way to indicate errors according to [REST architecture](http://code.tutsplus.com/tutorials/a-beginners-guide-to-http-and-rest--net-16340).

**Comment by r3wt** [comment]
Not my fault everyone else is retarded.

**Comment by alexweissman** [comment]
Why?  For using HTTP the way it was meant to be used?

**Comment by r3wt** [comment]
I just think that is not appropriate to use HTTP status codes for thrown exceptions. Google and Facebook, StackOverflow use JSON (googles is success (true || false), so pretty similar in strategy as mine. The theory here is that by returning JSON, you can expand your response objects at anytime, where as relying on http status holes your hands are pretty much tied on the type of state your represent in your response. 

What i have presented is what i have found to be the optimal solution based on experience as well as indicators from tech giants on how they approach representing error state in their api's.

**Comment by alexweissman** [comment]
Yes but why invent some arbitrary structures on top of the response?  Then any client who consumes your API has to know exactly what to expect from your response structure (i.e., a JSON object with two keys, 'error' and 'message').

I understand what you're saying, and this situation is clearly not a memoryless transaction.  But I feel like it would make more sense to do one of the following things:

1. Pick another HTTP code to indicate "captcha must be reloaded";
2. Create a separate resource URI (e.g. `/login/refresh-captcha`) that returns `true` or `false`, thus separating the response from the login attempt (failure) from the subsequent followup action (refresh the captcha)
