### ISSUE TITLE
Best way to encapsulate a website into UserFrosting ?

### ISSUE THREAD

**Issue by mehdi-aouadi** [alexweissman/UserFrosting#365]
Hi,

Thank you for this framework it looks great !
I already have a website and want to encapsulate it into the UserFrosting framework. I want to manage users registrations and acces control to my website.
I already installed user frosting and want to know what is the best way to do that ?
I read the tutorials that shows how to create pages within UF but I already have my website. I juste want to create a new entry in the navigation bar that points on the home page of my website.
Can you please help me to do that ?

Best Regards,
MA

**Comment by X-Anonymous-Y** [comment]
side bar on the home page?
the home page only have a nav bar!
I think you mean the dashboard (sb admin) page? right?

**Comment by X-Anonymous-Y** [comment]
if that is correct then you find the file under:
userfrosting->templates->themes->default->menus->sidebar.html

and for the home page, see below:
userfrosting->templates->common->components->main-nav.html

**Comment by mehdi-aouadi** [comment]
Yes I mean navbar, I edited my question.
And I nedd just to add an entry in the navbar that points the index.php of my website ?! I don't just need a redirection, I want to encapsulate the whole website within UF. I mean I just the registred users in UF to access my website.

**Comment by alexweissman** [comment]
Hi @mehdi-aouadi, this is going to depend on how your current website it structured, and what technologies it currently uses.  UF is not a "drop-in" component; you'll need to carefully restructure and integrate your code into the core UF structure.

So, my questions are:
- Would you consider your current website to be "MVC"?  Do you already have separate layers for the data model, controller logic, and presentation?
- Do you use a front controller?
- Do you use a templating engine?

This would help me to better understand where you're at and make a recommendation.  I would also highly suggest that you read through [Navigating UserFrosting](http://www.userfrosting.com/navigating/) to help you understand the basic layout.

**Comment by mehdi-aouadi** [comment]
Hi @alexweissman ,

I am actually using [PHP Addressbook](https://github.com/chatelao/php-addressbook) (an open source address book web tool) and want to manage the users using UF (in addressbook there is no registration, user administration ... ).
I believe it is not MVC and don't se a front controller or a templating engine.
I already read the tutorials in your website explaining how to create pages and how UF is designed. But I want to know if there is an easy way to integrate the Addressbook tool within UF or I nedd to restructure the entire website ?

**Comment by alexweissman** [comment]
Just browsing through that project's code I can tell you that you are correct, it is not organized as MVC.  It appears to use the outdated practice of putting all the code (logic, database/model interactions, and HTML rendering) into individual files that then post back to themselves. There are also some security issues, namely that it uses parameter interpolation for DB calls (e.g. https://github.com/chatelao/php-addressbook/blob/master/group.php#L15) which could expose you to SQL injection.

This is all a shame, because it looks like the author has really put a lot of time and effort into creating and documenting the project.  Are you in touch with the author, or do you know if the project is actively maintained?  I'd say that with some careful rewriting and refactoring, it could be turned into a plugin for UserFrosting.

**Comment by mehdi-aouadi** [comment]
Unfortunately the project doesn't seem to be maintained since January 2015.
It is one of the rare free address book I found on the web. To be honest, I would have liked to develop my website from scratch but I don't have enough time and I need urgently an online address book with a user management layer.
I also found [PHP Kobo](http://www.phpkobo.com/) which generates a php scripts to create a simple address book ...
My goal is to adapt one of them so I can add the UserFrosting functionalities. I appreciate your idea to make that a UserFrosting plugin ! This could be a great feature. I can contribute but I need more details to understand what should be rewritten.

**Comment by alexweissman** [comment]
Sounds great!  We're still working out the kinks in the plugin system, but you can take a look at the [OAuth plugin](https://github.com/ssnukala/UserFrosting-OAuth) that's in development to get an idea of how a typical plugin would work.

Basically, I would start by inspecting the SQL tables that @chatelao's system creates.  This will give you a good idea of the underlying representation of users, groups, addresses, etc.  Then you can try to see how it relates to UserFrosting's tables.  For example, you might want to have UserFrosting's `user_id` field as a foreign key in PHP Address Book's user table.

Once you get the database structure figured out, you can look at implementing some model classes (basically, this is the layer that provides access to the database).  It might, for example, make sense to extend the [MySqlUser](https://github.com/alexweissman/UserFrosting/blob/master/userfrosting/models/mysql/MySqlUser.php) class to have additional fields like `address`, etc.  Or, you could create an entirely new class like `MySqlAddress` that simply references the user by `user_id`.  This will take some careful thought and planning, but I think you'd find the effort very fulfilling.

After that, it's just a matter of creating the templates (you can probably grab some of his HTML) and deciding how to integrate it into UF's views, and building the controllers that link your models to the views.

I'd do it myself, but unfortunately I don't have the time either :-/  If you do decide to go forward with it, I think it would be a good way to get yourself acquainted with MVC, Composer, and other aspects of modern PHP.  I'll be happy to answer any questions you have in the process.

**Comment by chatelao** [comment]
I'm the main author of php addressbook, feel free to contribute pull-requests to improve it. I will check them. The magic is not in the database (this one is trivial), all the converters and the z-push Integration for Android/iPhones.

**Comment by alexweissman** [comment]
Cool, thanks for replying.  I haven't tried to install your software personally - mainly I was just commenting on the overall architecture of your project.  Unfortunately I don't have time to work on it myself.  

I see it's an old project so maybe you already know this, but it seems to be heavily steeped in the PHP4 way of doing things.  If you're looking to continue development on it (note: that's **if**), you should look into:
- PDO and prepared queries
- Separating your code into model, view, and controller layers
- Using a front controller so that your URLs aren't tied to your file names
- Using Composer to include external dependencies
- Reading up about all of these things and more on www.phptherightway.com

Again, maybe you know about all of these things, and this is just an old project that you don't plan on maintaining.  But if you want to bring this project into the modern PHP community, and for any future PHP projects you start on, these are essential.

I'm not saying to go with a full-stack framework, but something lightweight like [Slim](www.slimframework.com) will make organizing your code into an MVC structure a lot easier.

**Comment by alexweissman** [comment]
Please re-open this issue if you'd like to continue discussing.
